name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete old images
        run: |
          images=$(sudo docker images --filter=reference='eliotatlani31/face-auth-server' --format "{{.ID}} {{.CreatedAt}}" | sort -k2 | head -n -1 | awk '{print $1}')
          if [ -n "$images" ]; then
            sudo docker rmi -f $images
          fi
      - name: Pull Docker image
        run: sudo docker pull eliotatlani31/face-auth-server:latest
      - name: Delete Old Docker
        run: sudo docker rm -f face-auth-server || true
      - name: Run Docker container
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          # Add more environment variables as needed
        run: |
          sudo docker run -d -p 8000:8000 \
          -e SECRET_KEY=${SECRET_KEY} \
          -e ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES} \
          --name face-auth-server \
          eliotatlani31/face-auth-server
